### PR TITLE
Enable API doc generation using api-extractor

### PR DESCRIPTION
**Pull request by jeremymeng**
## Description

Add api-extractor

# Reference to any github issues
- #195

### CODE REVIEW

**Comment by amarzavery** [comment]
OPS Build status updates of commit _[7b9fec2](https://github.com/jeremymeng/azure-event-hubs-node/pull/199/commits/7b9fec2b55f6b9eb0b1bca3ab3a9d68f0eac243b)_: 

:clock10: **Preparing**: average preparing time is _49 sec(s)_

**Comment by jeremymeng** [comment]
@ramya-rao-a

**Comment by amarzavery** [comment]
OPS Build status updates of commit _[7b9fec2](https://github.com/jeremymeng/azure-event-hubs-node/pull/199/commits/7b9fec2b55f6b9eb0b1bca3ab3a9d68f0eac243b)_: 

:clock10: **Incremental building**: average incremental building time is _17 sec(s)_

**Comment by amarzavery** [comment]
OPS Build status updates of commit _[7b9fec2](https://github.com/jeremymeng/azure-event-hubs-node/pull/199/commits/7b9fec2b55f6b9eb0b1bca3ab3a9d68f0eac243b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[client/api-extractor.json](https://github.com/jeremymeng/azure-event-hubs-node/blob/add-api-extractor/client/api-extractor.json) | :white_check_mark:Succeeded | |
[client/package-lock.json](https://github.com/jeremymeng/azure-event-hubs-node/blob/add-api-extractor/client/package-lock.json) | :white_check_mark:Succeeded | |
[client/package.json](https://github.com/jeremymeng/azure-event-hubs-node/blob/add-api-extractor/client/package.json) | :white_check_mark:Succeeded | |
[processor/api-extractor.json](https://github.com/jeremymeng/azure-event-hubs-node/blob/add-api-extractor/processor/api-extractor.json) | :white_check_mark:Succeeded | |
[processor/package-lock.json](https://github.com/jeremymeng/azure-event-hubs-node/blob/add-api-extractor/processor/package-lock.json) | :white_check_mark:Succeeded | |
[processor/package.json](https://github.com/jeremymeng/azure-event-hubs-node/blob/add-api-extractor/processor/package.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C13%5Cdef8de6f-0c8d-6946-03eb-eef8a12e22c6%5CPullRequest%5C201902131921001023-199%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=MphokxuPNiO15HZfNvOKkLla2u60fXswlOo8ps6QDDs%3D&st=2019-02-13T19%3A17%3A00Z&se=2019-03-16T19%3A22%3A00Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by ramya-rao-a** [comment]
Fixes #201

**Pull request merged**
