### PR TITLE
Update expected error in invalid partition id test

### PR DESCRIPTION
**Pull request by jeremymeng**
## Description

After upgrading to the latest amqp-common, The type of thrown errors are now ArgumentOutOfRangeError.

# Reference to any github issues
- #179

### CODE REVIEW

**Comment by amarzavery** [comment]
OPS Build status updates of commit _[fb4623e](https://github.com/jeremymeng/azure-event-hubs-node/pull/187/commits/fb4623e0d4750a6b4d00b415d5afc73aa40044f2)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 1 sec(s)_

**Comment by jeremymeng** [comment]
@ramya-rao-a

**Comment by amarzavery** [comment]
OPS Build status updates of commit _[fb4623e](https://github.com/jeremymeng/azure-event-hubs-node/pull/187/commits/fb4623e0d4750a6b4d00b415d5afc73aa40044f2)_: 

:clock10: **Incremental building**: average incremental building time is _20 sec(s)_

**Comment by amarzavery** [comment]
OPS Build status updates of commit _[fb4623e](https://github.com/jeremymeng/azure-event-hubs-node/pull/187/commits/fb4623e0d4750a6b4d00b415d5afc73aa40044f2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[client/tests/client.spec.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/fix-client-tests/client/tests/client.spec.ts) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C6%5Cdef8de6f-0c8d-6946-03eb-eef8a12e22c6%5CPullRequest%5C201902062212335230-187%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=bpWVrK%2BWXEb5mEyenSfrJPv0lL8DphMsvwKGKQBPwcQ%3D&st=2019-02-06T22%3A09%3A10Z&se=2019-03-09T22%3A14%3A10Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by amarzavery** [comment]
OPS Build status updates of commit _[4c7e143](https://github.com/jeremymeng/azure-event-hubs-node/pull/187/commits/4c7e1439e563e3eece541dc82a92a454777787aa)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 4 sec(s)_

**Comment by amarzavery** [comment]
OPS Build status updates of commit _[4c7e143](https://github.com/jeremymeng/azure-event-hubs-node/pull/187/commits/4c7e1439e563e3eece541dc82a92a454777787aa)_: 

:clock10: **Incremental building**: average incremental building time is _20 sec(s)_

**Comment by amarzavery** [comment]
OPS Build status updates of commit _[4c7e143](https://github.com/jeremymeng/azure-event-hubs-node/pull/187/commits/4c7e1439e563e3eece541dc82a92a454777787aa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[client/tests/client.spec.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/fix-client-tests/client/tests/client.spec.ts) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C6%5Cdef8de6f-0c8d-6946-03eb-eef8a12e22c6%5CPullRequest%5C201902062310189775-187%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=2Jj5jBjBZsaRPHWEWzXL9obxFgzinuEsNH5hZBhFypM%3D&st=2019-02-06T23%3A06%3A55Z&se=2019-03-09T23%3A11%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jeremymeng** [comment]
Looks like this is actually a service side change. Without upgrading the amqp-common package the invalid partition id tests failed the same.

**Comment by ramya-rao-a** [comment]
> Looks like this is actually a service side change. Without upgrading the amqp-common package the invalid partition id tests failed the same.

Yes, I see the same.

The error message seems to be more to the point: `The specified partition is invalid for an EventHub partition sender or receiver. It should be between 0 and 1`

Instead of testing the error name, lets test the error message like we do in https://github.com/Azure/azure-event-hubs-node/blob/v1.0.8-EH-December2018/client/tests/hubruntime.spec.ts#L85

I'll look into if there is any spec for the request we are making.

**Comment by amarzavery** [comment]
OPS Build status updates of commit _[60314fa](https://github.com/jeremymeng/azure-event-hubs-node/pull/187/commits/60314fa0f0ba41830a3dc0cc6ece46a21d2c76df)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 6 sec(s)_

**Comment by amarzavery** [comment]
OPS Build status updates of commit _[60314fa](https://github.com/jeremymeng/azure-event-hubs-node/pull/187/commits/60314fa0f0ba41830a3dc0cc6ece46a21d2c76df)_: 

:clock10: **Incremental building**: average incremental building time is _20 sec(s)_

**Comment by amarzavery** [comment]
OPS Build status updates of commit _[60314fa](https://github.com/jeremymeng/azure-event-hubs-node/pull/187/commits/60314fa0f0ba41830a3dc0cc6ece46a21d2c76df)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[client/tests/client.spec.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/fix-client-tests/client/tests/client.spec.ts) | :white_check_mark:Succeeded | |
[client/tests/receiver.spec.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/fix-client-tests/client/tests/receiver.spec.ts) | :white_check_mark:Succeeded | |
[client/tests/sender.spec.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/fix-client-tests/client/tests/sender.spec.ts) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C7%5Cdef8de6f-0c8d-6946-03eb-eef8a12e22c6%5CPullRequest%5C201902071831244326-187%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=q1bbJYIt2DSuSomGo%2F%2FJjNHArfMz66zOZczZaVS1iwE%3D&st=2019-02-07T18%3A28%3A33Z&se=2019-03-10T18%3A33%3A33Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jeremymeng** [comment]
@ramya-rao-a Good point on verifying the error messages. I update this test and a few others to do that.

**Pull request merged**
