### PR TITLE
Update Copyright header

### PR DESCRIPTION
**Pull request by jeremymeng**

### CODE REVIEW

**Comment by amarzavery** [comment]
OPS Build status updates of commit _[63cd159](https://github.com/jeremymeng/azure-event-hubs-node/pull/197/commits/63cd1594995c8099752480b0126db9b64b148a0e)_: 

:clock10: **Preparing**: average preparing time is _51 sec(s)_

**Comment by jeremymeng** [comment]
@ramya-rao-a @AlexGhiondea

**Comment by amarzavery** [comment]
OPS Build status updates of commit _[63cd159](https://github.com/jeremymeng/azure-event-hubs-node/pull/197/commits/63cd1594995c8099752480b0126db9b64b148a0e)_: 

:clock10: **Incremental building**: average incremental building time is _18 sec(s)_

**Comment by amarzavery** [comment]
OPS Build status updates of commit _[63cd159](https://github.com/jeremymeng/azure-event-hubs-node/pull/197/commits/63cd1594995c8099752480b0126db9b64b148a0e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[client/examples/batchReceive.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/client/examples/batchReceive.ts) | :white_check_mark:Succeeded | |
[client/examples/batchSendReceive.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/client/examples/batchSendReceive.ts) | :white_check_mark:Succeeded | |
[client/examples/createEpochReceiver.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/client/examples/createEpochReceiver.ts) | :white_check_mark:Succeeded | |
[client/examples/getHubRuntimeInfo.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/client/examples/getHubRuntimeInfo.ts) | :white_check_mark:Succeeded | |
[client/examples/iotGetHubRuntimeInfo.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/client/examples/iotGetHubRuntimeInfo.ts) | :white_check_mark:Succeeded | |
[client/examples/sendReceiveWithInteractiveAuth.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/client/examples/sendReceiveWithInteractiveAuth.ts) | :white_check_mark:Succeeded | |
[client/examples/sendReceiveWithSPAuth.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/client/examples/sendReceiveWithSPAuth.ts) | :white_check_mark:Succeeded | |
[client/examples/simpleSendReceive.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/client/examples/simpleSendReceive.ts) | :white_check_mark:Succeeded | |
[client/examples/simpleSender.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/client/examples/simpleSender.ts) | :white_check_mark:Succeeded | |
[client/examples/streamingReceive.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/client/examples/streamingReceive.ts) | :white_check_mark:Succeeded | |
[client/lib/batchingReceiver.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/client/lib/batchingReceiver.ts) | :white_check_mark:Succeeded | |
[client/lib/connectionContext.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/client/lib/connectionContext.ts) | :white_check_mark:Succeeded | |
[client/lib/eventData.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/client/lib/eventData.ts) | :white_check_mark:Succeeded | |
[client/lib/eventHubClient.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/client/lib/eventHubClient.ts) | :white_check_mark:Succeeded | |
[client/lib/eventHubReceiver.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/client/lib/eventHubReceiver.ts) | :white_check_mark:Succeeded | |
[client/lib/eventHubSender.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/client/lib/eventHubSender.ts) | :white_check_mark:Succeeded | |
[client/lib/eventPosition.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/client/lib/eventPosition.ts) | :white_check_mark:Succeeded | |
[client/lib/index.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/client/lib/index.ts) | :white_check_mark:Succeeded | |
[client/lib/iothub/iothubClient.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/client/lib/iothub/iothubClient.ts) | :white_check_mark:Succeeded | |
[client/lib/linkEntity.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/client/lib/linkEntity.ts) | :white_check_mark:Succeeded | |
[client/lib/log.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/client/lib/log.ts) | :white_check_mark:Succeeded | |
[client/lib/managementClient.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/client/lib/managementClient.ts) | :white_check_mark:Succeeded | |
[client/lib/streamingReceiver.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/client/lib/streamingReceiver.ts) | :white_check_mark:Succeeded | |
[client/lib/util/constants.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/client/lib/util/constants.ts) | :white_check_mark:Succeeded | |
[client/tests/client.spec.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/client/tests/client.spec.ts) | :white_check_mark:Succeeded | |
[client/tests/eventPosition.spec.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/client/tests/eventPosition.spec.ts) | :white_check_mark:Succeeded | |
[client/tests/eventdata.spec.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/client/tests/eventdata.spec.ts) | :white_check_mark:Succeeded | |
[client/tests/hubruntime.spec.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/client/tests/hubruntime.spec.ts) | :white_check_mark:Succeeded | |
[client/tests/iothub.spec.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/client/tests/iothub.spec.ts) | :white_check_mark:Succeeded | |
[client/tests/misc.spec.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/client/tests/misc.spec.ts) | :white_check_mark:Succeeded | |
[client/tests/receiver.spec.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/client/tests/receiver.spec.ts) | :white_check_mark:Succeeded | |
[client/tests/sender.spec.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/client/tests/sender.spec.ts) | :white_check_mark:Succeeded | |
[processor/examples/iothubEph.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/processor/examples/iothubEph.ts) | :white_check_mark:Succeeded | |
[processor/examples/multiEph.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/processor/examples/multiEph.ts) | :white_check_mark:Succeeded | |
[processor/examples/sendBatch.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/processor/examples/sendBatch.ts) | :white_check_mark:Succeeded | |
[processor/examples/singleEph.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/processor/examples/singleEph.ts) | :white_check_mark:Succeeded | |
[processor/lib/azureBlob.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/processor/lib/azureBlob.ts) | :white_check_mark:Succeeded | |
[processor/lib/azureBlobLease.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/processor/lib/azureBlobLease.ts) | :white_check_mark:Succeeded | |
[processor/lib/azureStorageCheckpointLeaseManager.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/processor/lib/azureStorageCheckpointLeaseManager.ts) | :white_check_mark:Succeeded | |
[processor/lib/baseLease.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/processor/lib/baseLease.ts) | :white_check_mark:Succeeded | |
[processor/lib/blobService.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/processor/lib/blobService.ts) | :white_check_mark:Succeeded | |
[processor/lib/checkpointInfo.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/processor/lib/checkpointInfo.ts) | :white_check_mark:Succeeded | |
[processor/lib/checkpointManager.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/processor/lib/checkpointManager.ts) | :white_check_mark:Succeeded | |
[processor/lib/completeLease.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/processor/lib/completeLease.ts) | :white_check_mark:Succeeded | |
[processor/lib/eventProcessorHost.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/processor/lib/eventProcessorHost.ts) | :white_check_mark:Succeeded | |
[processor/lib/hostContext.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/processor/lib/hostContext.ts) | :white_check_mark:Succeeded | |
[processor/lib/index.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/processor/lib/index.ts) | :white_check_mark:Succeeded | |
[processor/lib/leaseManager.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/processor/lib/leaseManager.ts) | :white_check_mark:Succeeded | |
[processor/lib/log.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/processor/lib/log.ts) | :white_check_mark:Succeeded | |
[processor/lib/modelTypes.ts](https://github.com/jeremymeng/azure-event-hubs-node/blob/update-license/processor/lib/modelTypes.ts) | :white_check_mark:Succeeded | |

This comment lists only the first 50 files in the pull request.
For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C13%5Cdef8de6f-0c8d-6946-03eb-eef8a12e22c6%5CPullRequest%5C201902130338276876-197%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=iq7%2BP%2BcdFRL%2FTvfBXYGyx4SbPR%2FS%2B8T24fiqQu8m9Mo%3D&st=2019-02-13T03%3A34%3A29Z&se=2019-03-16T03%3A39%3A29Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
