### PR TITLE
[NO MERGE] [For Review] prepare for moving into central repro

### PR DESCRIPTION
**Pull request by jeremymeng**
/cc @ramya-rao-a

### CODE REVIEW

**Comment by amarzavery** [comment]
OPS Build status updates of commit _[b702433](https://github.com/jeremymeng/azure-event-hubs-node/pull/193/commits/b702433312fd5d6df7374b6e2f9b7ea2cbc17b6a)_: 

:clock10: **Preparing**: average preparing time is _57 sec(s)_

**Comment by amarzavery** [comment]
OPS Build status updates of commit _[b702433](https://github.com/jeremymeng/azure-event-hubs-node/pull/193/commits/b702433312fd5d6df7374b6e2f9b7ea2cbc17b6a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Publish service&#39;s config file: .openpublishing.publish.config.json is not found. Exception: 

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C12%5Cdef8de6f-0c8d-6946-03eb-eef8a12e22c6%5CPullRequest%5C201902122054427193-193%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=rMjEVf8dKfwu%2Bwo9wiyq71WT6jnyknfJ4frHpL0y%2Bgw%3D&st=2019-02-12T20%3A49%3A54Z&se=2019-03-15T20%3A54%3A54Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by ramya-rao-a** [comment]
Thanks @jeremymeng!
cc @bterlson

**Comment by ramya-rao-a** [comment]
This is slightly tough to review as well because of https://github.com/Azure/azure-event-hubs-node/pull/193/commits/e754570c5106ce8b83ae78155dc624a6c90d0db4

@bterlson I guess we will have review each commit separately before and after the above commit

**Comment by jeremymeng** [comment]
> This is slightly tough to review as well because of [e754570](https://github.com/Azure/azure-event-hubs-node/commit/e754570c5106ce8b83ae78155dc624a6c90d0db4)

Sorry for that. I tried to rebase/shuffle/squash changes, but the renaming made them hard to do without re-doing the changes.

**Comment by ramya-rao-a** [comment]
Hmmm... I can take this branch, undo the commits till https://github.com/Azure/azure-event-hubs-node/commit/e754570c5106ce8b83ae78155dc624a6c90d0db4, create a new PR.

Then another for just the move.

Then another for the remaining commits.

Thoughts?

**Comment by AlexGhiondea** [comment]
@jeremymeng Let's try and have multiple smaller PRs in this repo to make it easier for the reviewers to look at the code. We don't have a lot of experience in this repo and making smaller incremental changes are better.

Once we merge all of those PRs (that move this repo's build system to the one we use in the central repo) we can do a one time move of the repo over -- that will be easier to review (and is what we did for Service Bus and what we want to use as a pattern for how to move repos going forward).

**Comment by jeremymeng** [comment]
@AlexGhiondea sounds good. Did you create a a new target branch in the old repo for the service bus PR? or is it okay to merge the changes into `master`?  If we want the former, does anyone has permission to create a branch in this repo?

**Comment by jeremymeng** [comment]
Abandoning in favor of smaller PRs

**Comment by ramya-rao-a** [comment]
> Did you create a a new target branch in the old repo for the service bus PR or is it okay to merge the changes into `master`?

No, we merged to master.

> If we want the former, does anyone has permission to create a branch in this repo?

Can you elaborate on what you mean by the "former"?

**Comment by jeremymeng** [comment]
> Can you elaborate on what you mean by the "former"?

Thanks! I saw the changes in the `master`.  I was under an incorrect impression that we don't want to change `master` thus suggesting PR against a different branch.

**Pull request closed without merging**
